public class ToodledoResponseClass {
	public String id{get;set;}
	public String title{get;set;}
	public Long duedate{get;set;}
	public String status{get;set;}
	public String priority{get;set;}
	public String note{get;set;}
	public Long modified{get;set;} 
	public Long completed{get;set;}
	public String folder{get;set;}
	public String star{get;set;}
	public String tag{get;set;}
	public String duedatemod{get;set;}
	public ToodledoResponseClass(){}
}